import {
  Client,
  Exchange,
  SSRExchange,
  createClient,
  fetchExchange,
  ssrExchange,
} from "@urql/core"
import { devtoolsExchange } from "@urql/devtools"
import { cacheExchange } from "@urql/exchange-graphcache"
import fetch from "isomorphic-unfetch"
import { Environment, deploymentEnvironment } from "./env"
import { authLink } from "./graphql/client"

export const GRAPHQL_URL = (token: string | null) =>
  process.env["DAILP_API_URL"] + (token ? "/graphql-edit" : "/graphql")
export const WP_GRAPHQL_URL = "https://wp.dailp.northeastern.edu/graphql"

export const sharedCache = cacheExchange({
  schema: {
    __schema: {
      queryType: { name: "Query" },
      mutationType: { name: "Mutation" },
      subscriptionType: null,
    },
  },
  resolvers: {
    Query: {
      document: (_, args, cache) => {
        return cache.keyOfEntity({
          __typename: "AnnotatedDoc",
          slug: args["slug"]!,
        })
      },
    },
  },
  // This defines how data should be keyed
  // Using "null" as a key means the data should be cached on its parent
  keys: {
    Contributor: () => null,
    Date: () => null,
    MorphemeTag: () => null,
    PageImage: () => null,
    PositionInDocument: () => null,
    WordSegment: () => null,
    DocumentPage: () => null,
    AnnotatedDoc: (data) => data["slug"] as string,
    AudioSlice: (data) => data["sliceId"] as string,
    DocumentCollection: (data) => data["slug"] as string,
  },
})

/**
 * This is the client SSR exchange.
 * Shared between WP and DAILP gql endpoints.
 */
export const clientSsrExchange = ssrExchange({
  isClient: true,
  initialState: {},
  // this lets us rehydrate our pages quickly but still get the most updated
  // data in a timely manner
  staleWhileRevalidate: true,
})

/**
 * These are clients used to make requests in `prerender` functions. They do not
 * have any auth or SSR exchanges.
 */
export const serverSideClients = {
  dailp: createClient({
    url: GRAPHQL_URL(null),
    exchanges: [sharedCache, fetchExchange],
  }),
  wordpress: createClient({
    url: WP_GRAPHQL_URL,
    exchanges: [sharedCache, fetchExchange],
  }),
}

const maybeDevExchange =
  deploymentEnvironment === Environment.Production ? [] : [devtoolsExchange]

/**
 * A custom client that will point at the DAILP GraphQL server.
 * Has the following exchanges by default:
 * - devtoolsExchange (not added in production)
 * - sharedCache
 * - Any caller-specified exchanges (see `exchanges` param)
 * - authLink (if a token is provided)
 * - fetchExchange
 * @param suspense - if queries should suspend instead of giving a loading state (for SSR)
 * @param exchanges - extra exchanges the caller needs (ie. a specific client/server SSR exchange)
 * @param token - an auth token for doing mutations (TODO: this shouldn't be passed in, but dynamically generated by the authLink)
 * @returns
 */
const customClient = (
  suspense: boolean,
  exchanges: Exchange[],
  token: string | null
) =>
  createClient({
    url: GRAPHQL_URL(token),
    exchanges: [
      ...maybeDevExchange,
      sharedCache,
      ...exchanges,
      ...(token ? [authLink(token)] : []),
      fetchExchange,
    ],
    suspense,
    fetch, // TODO: is this needed?
  })

/**
 * Create a fresh SSR exchange and client to serve a single SSR request.
 * */
export function ssrClientAndExchange(): [SSRExchange, Client] {
  // We want to make a new SSR exchange every time so that only queries on the individual request and captured and sent to the client.
  const ssr = ssrExchange({ initialState: undefined, isClient: false })
  // We turn suspense on for the server-side SSR client so it can await rendering the whole tree, along with queries.
  const client = customClient(true, [ssr], null)
  return [ssr, client]
}

export const clientSideGraphqlClient = (token: string | null) =>
  customClient(false, [clientSsrExchange], token)
