[package]
name = "dailp"
version = "0.2.0"
authors = ["Taylor Snead <taylorsnead@gmail.com>"]
edition = "2018"

[lib]
name = "dailp"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0", features = ["derive"]}
tera = "1"
tokio = { version = "0.2", features = ["full", "time"] }
anyhow = "1.0"
itertools = "0.9"
async-graphql = "2.0"
futures = "0.3"
mongodb = "1.1"
lazy_static = "1.4"
regex = "1.3"
unicode-normalization = "0.1"
chrono = {version = "0.4", features = ["serde"]}
nom = "5"
slug = "0.1"
