[package]
name = "dailp"
version = "0.4.0"
authors = ["Taylor Snead <taylor@snead.xyz>"]
edition = "2018"

[lib]
name = "dailp"
path = "src/lib.rs"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
tokio = { version = "0.2", features = ["full", "time"] }
anyhow = "1.0"
itertools = "0.9"
async-graphql = "2.4"
futures = "0.3"
mongodb = {git = "https://github.com/mongodb/mongo-rust-driver", rev = "6067e98fedcdabc8b8fce4cdd5a1d6e155929a38"}
lazy_static = "1.4"
regex = "1.3"
unicode-normalization = "0.1"
chrono = {version = "0.4", features = ["serde"]}
nom = "5"
slug = "0.1"
maplit = "1"
