Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: dailp
      Description: Digital Archive of American Indian Languages Preservation and Perseverence
      Repository: ${env:GIT_REPOSITORY_URL}
      OauthToken: ${env:OAUTH_TOKEN}
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      CustomRules:
        - Source: "/<*>"
          Status: 404-200
          Target: "/404.html"
        # Allow us to access the corresponding graphql environment (dev or prod)
        # at the path /graphql. Then the front-end doesn't have to know the exact url.
        - Source: "/graphql"
          Status: 200
          Target:
            Fn::Sub:
              - https://${RestApiId}.execute-api.${self:provider.region}.amazonaws.com/${opt:stage}/graphql
              - RestApiId: !Ref ApiGatewayRestApi
      BuildSpec:
        Fn::Sub:
          - |-
            version: 1
            env:
              variables:
                DAILP_GRAPHQL_URL: https://${RestApiId}.execute-api.${self:provider.region}.amazonaws.com/${opt:stage}/graphql
            frontend:
              artifacts:
                baseDirectory: website/public
                files:
                  - "**/*"
              phases:
                build:
                  commands:
                    - cd website
                    - yarn install
                    - yarn build
                    - cd ..
              cache:
                paths:
                  - website/node_modules
                  - target
            customHeaders:
              - pattern: "**/*.{json,html}"
                headers:
                  - key: "Cache-Control"
                    value: "public, max-age=0, must-revalidate"
          - RestApiId: !Ref ApiGatewayRestApi
  AmplifyMainBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: main
      AppId: !GetAtt AmplifyApp.AppId
      Description: Main Branch
      # Use a build hook at the end of our GH Action instead.
      EnableAutoBuild: false
      # But do build PR previews.
      EnablePullRequestPreview: true

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain
