# This is a basic workflow to help you get started with Actions

name: Development Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [dev]
    paths-ignore:
      - "**/README.md"
      - "**/readme.md"
      - "doc/**/*.md"
env:
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
  AWS_SUBNET_PRIMARY: ${{ secrets.AWS_SUBNET_PRIMARY }}
  AWS_SUBNET_SECONDARY0: ${{ secrets.AWS_SUBNET_SECONDARY0 }}
  AWS_SUBNET_SECONDARY1: ${{ secrets.AWS_SUBNET_SECONDARY1 }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  GIT_REPOSITORY_URL: https://github.com/${{ github.repository }}
  OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
  RUST_LOG: info
  TF_STAGE: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: Development
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Cargo Dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          default: true
      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'types/**'
              - 'graphql/**'
              - 'flake.nix'
              - 'terraform/**'
            data:
              - 'types/**'
              - 'migration/**'
              - 'graphql/**'
            rust:
              - '**/*.rs'
              - 'Cargo.lock'
      - name: Cache docker images
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Run unit tests
        if: steps.filter.outputs.rust == 'true'
        run: cargo test --release
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
          install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Add public IP to AWS security group
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-security-group-id: ${{ secrets.AWS_DEPLOYMENT_SECURITY_GROUP }}
          port: "22"
          to-port: "22"
          protocol: "tcp"
      - name: Deploy back-end to AWS via terraform
        if: steps.filter.outputs.backend == 'true'
        run: |
          nix build --impure
          cp -f ./result/config.tf.json ./config.tf.json
          nix develop --impure --command plan
      - name: Encode documents as TEI and database entries
        if: steps.filter.outputs.data == 'true'
        run: |
          export DAILP_GRAPHQL_URL=$(terraform output functions_url)/graphql
          cd migration
          cargo run --release
      - name: Publish website
        run: |
          curl -X POST -d {} -H "Content-Type:application/json" "$(terraform output amplify_webhook)"
