name: Infrastructure Health Check

on:
  workflow_dispatch:
    inputs: 
      applyTo:
        required: true
        default: Development
        type: choice
        description: Which environment do you want to test against?
        options:
          - Development
          - Staging/UAT
          - Production
jobs:
  check_bastion:
    name: Check Bastion EC2
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    environment:
      name: ${{ inputs.applyTo == 'Production' && 'Production' || 'Development'}}
      deployment: false
    env:
      DATABASE_PASSWORD:  ${{ inputs.applyTo == 'Staging/UAT' && secrets.UAT_DATABASE_PASSWORD || secrets.DATABASE_PASSWORD }}
      BASTION_ID: ${{ (inputs.applyTo == 'Staging/UAT' && secrets.UAT_EC2_INSTANCE) || (inputs.applyTo == 'Production' && secrets.EC2_INSTANCE) || secrets.DEV_EC2_INSTANCE}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Use binary cache for nix store
        uses: cachix/cachix-action@v12
        with:
          name: dailp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pushFilter: "(-dailp$|-dailp-|-terraform-config$|-source$|\\.tar\\.gz$|-output$|-plan$|-apply-now$|-apply$)"
      - name: Check Database Connection Path
        run: |
          echo "Retrieving terraform outputs..."
          nix run --impure -L .#tf-init
          DATABASE_ADDRESS=$(nix run --impure .#tf-output database_address)
          echo "Connecting to bastion via SSM..."
          aws ssm start-session \
          --target ${{ env.BASTION_ID }} \
          --document-name AWS-StartPortForwardingSessionToRemoteHost \
          --parameters '{"host":[ '"\"$DATABASE_ADDRESS\""' ],"portNumber":["5432"], "localPortNumber":["5432"]}' &
          SSM_PID=$!
          echo "Waiting for tunnel on localhost:5432..."
          for i in $(seq 1 15); do
            (echo > /dev/tcp/localhost/5432) >/dev/null 2>&1 && break
            sleep 1
          done
          export DATABASE_URL=postgres://dailp:$DATABASE_PASSWORD@localhost:5432/dailp
          psql "$DATABASE_URL" -c '\l'
          kill $SSM_PID
